AllCops:
  Exclude:
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/RescueStandardError:
  EnforcedStyle: implicit

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

StringLiterals:
  EnforcedStyle: single_quotes

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
    - '*.gemspec'
